# Generated by Django 6.0.4 on 2026-04-16 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travel_mode', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('car', 'Car'), ('bike', 'Bike'), ('cruise', 'Cruise'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='trip_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('visited', 'Visited'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('priority', models.IntegerField(default=1, help_text='1=High, 2=Medium, 3=Low')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='core.trip')),
            ],
            options={
                'ordering': ['priority', 'place_name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='trip_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('location_tag', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.trip')),
            ],
            options={
                'ordering': ['day_number', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('time_slot', models.TimeField()),
                ('activity', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='core.trip')),
            ],
            options={
                'ordering': ['day_number', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('food', 'Food & Dining'), ('hotel', 'Hotel / Stay'), ('shopping', 'Shopping'), ('tickets', 'Tickets / Entry'), ('misc', 'Miscellaneous')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.trip')),
            ],
            options={
                'ordering': ['date', 'category'],
            },
        ),
        migrations.CreateModel(
            name='VlogNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('script_title', models.CharField(max_length=200)),
                ('content_notes', models.TextField()),
                ('hook', models.CharField(blank=True, max_length=300)),
                ('thumbnail_idea', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_notes', to='core.trip')),
            ],
            options={
                'ordering': ['day_number', 'created_at'],
            },
        ),
    ]
